name: orium_invest
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  intl: ^0.19.0
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/banner1.png
    - assets/banner2.png
    - assets/banner3.png